---
extends: default

rules:
    new-line-at-end-of-file: disable
    line-length: disable
    indentation:
        indent-sequences: consistent
    comments:
        require-starting-space: true
        min-spaces-from-content: 1
    brackets:
        min-spaces-inside: 0
        max-spaces-inside: 1
        max-spaces-inside-empty: 0
    truthy:
        allowed-values: ['true', 'false', 'yes', 'no']
