---
- name: Copy the Exporter Exporter service file
  template:
    src: "exporter_exporter.{{ ansible_service_mgr | lower }}.j2"
    dest: "{{ lookup('vars', '_exporter_exporter_' + ansible_service_mgr + '_service').file }}"
    owner: root
    group: root
    mode: "{{ lookup('vars', '_exporter_exporter_' + ansible_service_mgr + '_service').mode }}"
  notify: restart exporter_exporter

- name: Create Exporter Exporter main configuration file
  template:
    src: expexp.yaml.j2
    dest: "{{ exporter_exporter_config_file }}"
    owner: root
    group: "{{ exporter_exporter_system_user }}"
    mode: 0640
  notify: restart exporter_exporter
